services:

  custom-nginx:
    container_name: custom_nginx
    image: custom_nginx
    build:
      context: container/
      dockerfile: Dockerfile
    ports:
      - target: 80
        host_ip: 127.0.0.1
        published: 8080
        protocol: tcp
        mode: host
